version: "3"
services:
    ganache:
        build:
            context: .
            dockerfile: Dockerfile.ganache
        ports:
            - "8545:8545"
    dapp:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - ganache
        links:
            - "ganache:ganache"
        command: sh -c "truffle migrate && npm start"


    